name = "Hugo Flax"
license = "Apache-2.0"
licenselink = "https://github.com/RyanSquared/hugo-flax/blob/master/LICENSE"
description = "A lightweight Hugo theme leveraging CSS Flexbox"
homepage = "https://github.com/RyanSquared/hugo-flax/"
tags = ["responsive", "minimal", "flexbox", "no-javascript"]
features = ["posts"]
min_version = "0.65"

[author]
name = "Ryan Heywood"
homepage = "https://github.com/RyanSquared"
